<?php

namespace SiteAPE\EvaluationBundle\Repository;

/**
 * ImageAboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAboRepository extends \Doctrine\ORM\EntityRepository
{
}
