<?php

namespace SiteAPE\PlateformeBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function maMethodeFindAll()
   {
      $queryBuilder = $this->createQueryBuilder('annonce');
      $query = $queryBuilder->getQuery();
      $results = $query->getResult();

      return $results;
   }

   public function FindParAuteurEtMot($auteur, $mot)
   {
       
        $queryBuilder = $this->createQueryBuilder('annonce');
        $queryBuilder->where('annonce.auteur = :auteur')
                     ->setParameter(':auteur', $auteur)
                     ->andWhere("annonce.titre LIKE '%$mot%'")
                     //->andWhere("annonce.titre LIKE '%développeur%'")
                     //->setParameter(':mot', $mot)
                     ->orderBy('annonce.date', 'DESC');
                     
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
   }

   public function getAnnonceCategorie($nomcateg)
   {
        $queryBuilder = $this->createQueryBuilder('annonce')->Join('annonce.categories', 'categorie')->addSelect('categorie');
        $queryBuilder->where('categorie.id = :id')
                     ->setParameter(':id', $nomcateg);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;

   }
}
